"""
Django settings for cacei_cuestionario project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_^bnw_ic^9-qtt9lza0o)y-yv)pi2b*#g917k9#+s1za9*+0ss'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

PREREQUISITES_APPS = [
    # Bootstrap Admin Interface
    'bootstrap3',
    'bootstrap_admin',
]

THIRD_PARTY_APPS = [
    # Themes
    'bootstrapform',
    
    # Aditional Packages
    'django.contrib.sites',
    'django.contrib.humanize',
    'metron',
    'transmeta',
    'account',
    'widget_tweaks',
    'questionnaire',
    'questionnaire.page',
]

PROJECT_APPS = [
    # Custom Apps
    'formulario',
    'resultado',
]

INSTALLED_APPS = [
    # Django batteries
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INSTALLED_APPS = PREREQUISITES_APPS + INSTALLED_APPS + THIRD_PARTY_APPS + PROJECT_APPS

SITE_ID = 1

MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    
    # Custom Middleware
    'django.middleware.locale.LocaleMiddleware',
    'questionnaire.request_cache.RequestCacheMiddleware',
    'account.middleware.LocaleMiddleware',
    'account.middleware.TimezoneMiddleware',

    # Custom Enforce Login Middleware
    'cacei_cuestionario.middleware.EnforceLoginMiddleware'
]

ROOT_URLCONF = 'cacei_cuestionario.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # Custom processors
                'account.context_processors.account',
                'cacei_cuestionario.context_processors.settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'cacei_cuestionario.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
# Examples: "http://media.lawrence.com/media/", "http://example.com/media/"
MEDIA_URL = '/media/'

FIXTURE_DIRS = [
    os.path.join(BASE_DIR, 'fixtures'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # 'compressor.finders.CompressorFinder',
]

LANGUAGES = (
    ('es', 'Spanish'),
    # ('en', 'English'),
    # ('de', 'German'),
)

# Configuration Email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

BOOTSTRAP_ADMIN_SIDEBAR_MENU = True
TRANSMETA_DEFAULT_LANGUAGE = 'es'

# Configuration Account
ACCOUNT_OPEN_SIGNUP = False
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = False
THEME_ACCOUNT_CONTACT_EMAIL = 'desarrollo@dilosung.com'
LOGIN_URL = '/cuenta/inicio'
LOGOUT_URL = '/cuenta/salir'

# Enforce Login Middleware public excludes and admin enforce
PUBLIC_URLS = [
    r'^%s' % STATIC_URL,
    r'^/jsi8n/',
    r'^/$',
    r'^/cuenta/',
    r'^/taller/',
    r'^/encuesta/',
    r'^/take/',
    r'^/q/',
    r'^/encuesta/finalizada/',
    
    # Remove on production
    r'^/admin/',
    r'^/__debug__/',
]

ADMIN_URLS = [
    # r'^/secret/stuff/$',
]

# Cuenta de correo que se presenta en el envio de correo
DEFAULT_FROM_EMAIL = "desarrollo@dilosung.com"

# Evitar que el middleware de acceso revise el flujo de verificacion de cuentas
AUTH_WORKFLOW_ENABLED = False
